Update azure-pipelines-4.yml for Azure Pipelines

diff --git a/azure-pipelines-4.yml b/azure-pipelines-4.yml
--- a/azure-pipelines-4.yml
+++ b/azure-pipelines-4.yml
@@ -1,8 +1,3 @@
-# Starter pipeline
-# Start with a minimal pipeline that you can customize to build and deploy your code.
-# Add steps that build, run tests, deploy, and more:
-# https://aka.ms/yaml
-
 trigger:
 - main
 
@@ -35,10 +30,19 @@ steps:
     command: 'plan'
     environmentServiceNameAzureRM: 'Azure for Students (8fd70241-1e7c-431a-91b1-be11c2bbe677)'
 
-- script: echo Hello, world!
-  displayName: 'Run a one-line script'
-
 - script: |
-    echo Add other tasks to build, test, and deploy your project.
-    echo See https://aka.ms/yaml
-  displayName: 'Run a multi-line script'
+    echo "Attempting to run plan again if state lock is active."
+    max_attempts=3
+    attempt=1
+    while [ $attempt -le $max_attempts ]; do
+        terraform plan -no-color
+        if [ $? -eq 0 ]; then
+            echo "Terraform plan succeeded."
+            break
+        else
+            echo "Attempt $attempt failed. Checking for state lock..."
+            sleep 10 # Wait for 10 seconds before retrying
+            attempt=$((attempt + 1))
+        fi
+    done
+  displayName: 'Run Terraform Plan with Retry'
